#include <string>
#include <iostream>
#include <vector>
#include <map>
#include <unordered_map>
#include <set>
#include <unordered_set>
#include <algorithm>
using namespace std;

#define N_LIMIT (int)1e6

/*
Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal.
***************
Tn=n(n+1)/2
Hn=n(2n−1)
n(n+1)/2 = m(2m−1)
n(n+1) = 2m(2m−1)
n = 2m-1
n +1 = 2m
 T285 = H143 = 286/2 = 143
 Tn = m(2m-1)
 check for Pentagonal
*/
bool isPentagon(uint64_t p)
{
    double  n = (1 + sqrt(1 + 24*p))/6;
    return (n == (int)n);
}
uint64_t Triangular_Pentagon_Hexa_number()
{
	uint64_t tph;

    for (uint64_t h = 144;; h++)
    {
        tph = h * 2*h -h;
        if (isPentagon(tph))
            return tph;
    }
    return tph;
}
 int main()
{    
    cout << "Triangular, pentagonal, and hexagonal: " << Triangular_Pentagon_Hexa_number() << endl;
    // Problem 45 Triangular, pentagonal, and hexagonal: 1533776805
    return 0;
}

